### ISSUE TITLE
Feature Flags

### ISSUE THREAD

**Issue by stefanwalther** [stefanwalther/sense-navigation#116]
In some scenarios not all features make sense. Would be great if I could place a file into the extension directory to enable/disable some features.
This would also make it easier to provide some experimental functionality, such as #63 

**Examples:**
- [ ] Jump to a specific sheet by Id only makes sense if the user has the possibility to found out the sheet id (which is not the case if Dev Hub is not available, eg. in Qlik Cloud)
- [ ] New features like e.g. document chaining or reload might also have to be disabled in Qlik Cloud.

**Tasks:**
- [ ] Implementation
- [ ] Default setup
- [ ] Default setup for Qlik Cloud

Solves #115

**Comment by stefanwalther** [comment]
Closing this.
